# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_auto_20170118_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='web',
            field=models.URLField(blank=True, null=True),
        ),
    ]
